dubbo :
  protocol :
    prot : 20880
    name  : dubbo
  application :
    name : service-consumer
  registry :
    address : zookeeper://192.168.8.3:2181
  #packageName : com.example.dubbo_provider.services

server :
  port : 8085

